---
- name: Install apache on ubuntu only
  hosts: all
  become: yes


  tasks:
    - name: Install apache on ubuntu
      apt: 
        name: apache2
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Start apache
      service: 
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['distribution'] == 'Ubuntu'