---
- name: Deploy Python App with Gunicorn
  hosts: all
  become: yes

  tasks:
    - name: Install Python and Gunicorn
      apt: 
        name: 
          - Python3
          - python3-pip
        state: present
    
    - name: Install Flask
      pip: 
        name: flask

    - name: copy flask App
      copy: 
        src: ./app.py
        dest: /home/ubuntu/app.py

    - name: Run Flask app with Gunicorn
      command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
      


  