---
- name: Install Java and Set Environment Variables
  hosts: all
  become: yes

  tasks:
    - name: Install OpenJDK
      apt:
        - name: openjdk-11-jdk
          state: present

    - name: Set JAVA_HOME in environment
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'


        