---
- name: setup HAProxy Load Balancer
  hosts: all
  become: yes

  tasks:
    - name: Install Proxy 
      apt: 
        name: haproxy
        state: present

    - name: Configure HAProxy
      copy: 
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
    
    - name: Restart HAProxy
      service:
        name: HAProxy
        state: Restarted
        enabled: yes
      