---
- name: Create a user and ensure directory exists
  hosts: all
  become: true

  tasks:
  - name: Create a user
    user:
      name: John
      state: preset
      groups: sudo
      shell: /bin/bash

  - name: Ensure that the directory exists
    file:
      path:
      state: /home/john/my_directory
      mode: '0755'
