---
- name: Update package cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install common packages
  package:
    name:
      - vim
      - curl
      - git
    state: present

- name: Create maintenance user
  user:
    name: maintainer
    shell: /bin/bash
    groups: sudo
    state: present